In [ ]:
import pandas as pd
import json
import csv
from openai import OpenAI
muj_api_klic = ""
client = OpenAI(api_key=muj_api_klic)

In [30]:
df1 = pd.read_json('vzorek_scraping_J.json')
df2 = pd.read_json('vzorek_scraping_l.json')
df3 = pd.read_json('vzorek_scraping_v.json')
df_carodejnice = pd.read_json('dataset_30_04.json')
df_carodejnice['url'] = df_carodejnice['url'].str.strip()

In [ ]:
spojeny_df = pd.concat([df1, df2, df3, df_carodejnice], axis=0, ignore_index=True)

,url,crawl,metadata,screenshotUrl,text,markdown,debug
0,https://www.calcalistech.com/ctechnews/article...,{'loadedUrl': 'https://www.calcalistech.com/ct...,{'canonicalUrl': 'https://www.calcalistech.com...,NaN,Cyber startup ActiveFence cuts 7% of workforce...,# Cyber startup ActiveFence cuts 7% of workfor...,{'requestHandlerMode': 'browser'}
1,https://www.calcalistech.com/ctechnews/article...,{'loadedUrl': 'https://www.calcalistech.com/ct...,{'canonicalUrl': 'https://www.calcalistech.com...,NaN,Armis lays off over half of Otorio’s staff fol...,# Armis lays off over half of Otorio’s staff f...,{'requestHandlerMode': 'browser'}
2,https://www.calcalistech.com/ctechnews/article...,{'loadedUrl': 'https://www.calcalistech.com/ct...,{'canonicalUrl': 'https://www.calcalistech.com...,NaN,AI startup D-ID lays off a quarter of its work...,# AI startup D-ID lays off a quarter of its wo...,{'requestHandlerMode': 'browser'}
3,https://sifted.eu/articles/arrival-sales-colla...,{'loadedUrl': 'https://sifted.eu/articles/arri...,{'canonicalUrl': 'https://sifted.eu/articles/a...,NaN,"EV startup Arrival shuts down operations, lays...","# EV startup Arrival shuts down operations, la...",{'requestHandlerMode': 'browser'}
4,https://blog.recroom.com/posts/2025/3/3/rec-ro...,{'loadedUrl': 'https://blog.recroom.com/posts/...,{'canonicalUrl': 'https://blog.recroom.com/pos...,NaN,Rec Room Update - March 2025 — ‎\nWe are shari...,# Rec Room Update - March 2025 — ‎\n\n_We are ...,{'requestHandlerMode': 'browser'}
...,...,...,...,...,...,...,...
3965,https://www.bizjournals.com/boston/news/2024/1...,{'loadedUrl': 'https://www.bizjournals.com/bos...,{'canonicalUrl': 'https://www.bizjournals.com/...,NaN,Akamai layoffs 2024: Company cuts 2.5% of its ...,# Akamai layoffs 2024: Company cuts 2.5% of it...,{'requestHandlerMode': 'browser'}
3966,https://www.sfgate.com/tech/article/applovin-l...,{'loadedUrl': 'https://www.sfgate.com/tech/art...,{'canonicalUrl': 'https://www.sfgate.com/tech/...,NaN,Bay Area tech company AppLovin announces layof...,# Bay Area tech company AppLovin announces lay...,{'requestHandlerMode': 'browser'}
3967,https://www.bizjournals.com/portland/news/2024...,{'loadedUrl': 'https://www.bizjournals.com/por...,{'canonicalUrl': 'https://www.bizjournals.com/...,NaN,Private equity-owned New Relic has more layoff...,# Private equity-owned New Relic has more layo...,{'requestHandlerMode': 'browser'}
3968,https://pitchbook.com/news/articles/bowery-ind...,{'loadedUrl': 'https://pitchbook.com/news/arti...,{'canonicalUrl': 'https://pitchbook.com/news/a...,NaN,"Bowery, once a leading indoor farming company ...","# Bowery, once a leading indoor farming compan...",{'requestHandlerMode': 'browser'}
3969,https://www.sfgate.com/tech/article/enphase-en...,{'loadedUrl': 'https://www.sfgate.com/tech/art...,{'canonicalUrl': 'https://www.sfgate.com/tech/...,NaN,"Down 80% in value since 2022, Bay Area solar g...","# Down 80% in value since 2022, Bay Area solar...",{'requestHandlerMode': 'browser'}

In [32]:
spojeny_df.to_json("vzorek_data_layoffs.json", orient='records', indent=4)

In [ ]:
df_selected = spojeny_df[['url', 'text']]
df_selected['url'] = df_selected['url'].str.strip()

C:\Users\zpjev\AppData\Local\Temp\ipykernel_17816\3625880623.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected['url'] = df_selected['url'].str.strip()

,url,text
0,https://www.calcalistech.com/ctechnews/article...,Cyber startup ActiveFence cuts 7% of workforce...
1,https://www.calcalistech.com/ctechnews/article...,Armis lays off over half of Otorio’s staff fol...
2,https://www.calcalistech.com/ctechnews/article...,AI startup D-ID lays off a quarter of its work...
3,https://sifted.eu/articles/arrival-sales-colla...,"EV startup Arrival shuts down operations, lays..."
4,https://blog.recroom.com/posts/2025/3/3/rec-ro...,Rec Room Update - March 2025 — ‎\nWe are shari...
...,...,...
3965,https://www.bizjournals.com/boston/news/2024/1...,Akamai layoffs 2024: Company cuts 2.5% of its ...
3966,https://www.sfgate.com/tech/article/applovin-l...,Bay Area tech company AppLovin announces layof...
3967,https://www.bizjournals.com/portland/news/2024...,Private equity-owned New Relic has more layoff...
3968,https://pitchbook.com/news/articles/bowery-ind...,"Bowery, once a leading indoor farming company ..."
3969,https://www.sfgate.com/tech/article/enphase-en...,"Down 80% in value since 2022, Bay Area solar g..."

In [34]:
dfAll = pd.read_csv('Layoffs.fyi_Tech_Layoffs_Tracker_Original.csv')
dfAll = dfAll.rename(columns={'Source': 'url'})
dfAll.insert(0, 'index', range(0, len(dfAll)))
dfAll['url'] = dfAll['url'].str.strip()
dfAll.tail(3)

,index,Company,Location HQ,# Laid Off,Date,%,Industry,url,Stage,$ Raised (mm),Country,Date Added
4023,4023,Panda Squad,SF Bay Area,6.0,13.3.2020,75%,Consumer,https://twitter.com/danielsinger/status/123854...,Seed,$1,United States,17.4.2020
4024,4024,Tamara Mellon,Los Angeles,20.0,12.3.2020,40%,Retail,https://layoffs.fyi/list/tamara-mellon/,Series C,$90,United States,31.3.2020
4025,4025,EasyPost,Salt Lake City,75.0,11.3.2020,NaN,Logistics,https://www.bizjournals.com/louisville/news/20...,Series A,$12,United States,31.3.2020

In [35]:
merged_df = pd.merge(dfAll, df_selected, on='url', how='left')
merged_df = merged_df.drop_duplicates()
df_no_duplicates = merged_df.drop_duplicates(subset='index', keep='first')
df_no_duplicates

,index,Company,Location HQ,# Laid Off,Date,%,Industry,url,Stage,$ Raised (mm),Country,Date Added,text
0,0,Tract,"London,Non-U.S.",NaN,3.4.2025,NaN,Real Estate,https://sifted.eu/articles/ai-proptech-startup...,Unknown,NaN,United Kingdom,6.4.2025,"AI proptech startup Tract shuts down\nTract, t..."
1,1,Automattic,SF Bay Area,281.0,2.4.2025,16%,Other,https://techcrunch.com/2025/04/02/wordpress-ma...,Series E,$986,United States,2.4.2025,WordPress maker Automattic lays off 16% of sta...
2,2,Canva,"Sydney,Non-U.S.",10.0,2.4.2025,NaN,Consumer,https://www.afr.com/technology/canva-shocks-em...,Unknown,$2500,Australia,2.4.2025,"Piano • Client Dashboard\nApr 2, 2025 – 8.00pm..."
3,3,WhyHive,"Melbourne,Non-U.S.",NaN,2.4.2025,100%,Data,https://www.startupdaily.net/topic/business/da...,Seed,NaN,Australia,6.4.2025,Data analytics startup WhyHive is shutting dow...
4,4,Northvolt,"Stockholm,Non-U.S.",2800.0,31.3.2025,62%,Energy,https://sifted.eu/articles/northvolt-lays-off-...,Unknown,$13800,Sweden,1.4.2025,Northvolt lays off half of staff as bankrupt b...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4137,4021,Service,Los Angeles,NaN,16.3.2020,100%,Travel,https://techcrunch.com/2020/03/16/travel-savin...,Seed,$5,United States,31.8.2020,NaN
4138,4022,HopSkipDrive,Los Angeles,8.0,13.3.2020,10%,Transportation,https://layoffs.fyi/2020/04/02/hopskipdrive-la...,Unknown,$45,United States,3.4.2020,[Layoff list ] EXCLUSIVE: HopSkipDrive laid of...
4139,4023,Panda Squad,SF Bay Area,6.0,13.3.2020,75%,Consumer,https://twitter.com/danielsinger/status/123854...,Seed,$1,United States,17.4.2020,NaN
4140,4024,Tamara Mellon,Los Angeles,20.0,12.3.2020,40%,Retail,https://layoffs.fyi/list/tamara-mellon/,Series C,$90,United States,31.3.2020,Tamara Mellon layoffs 3/12/20 - Google Sheets\...
4141,4025,EasyPost,Salt Lake City,75.0,11.3.2020,NaN,Logistics,https://www.bizjournals.com/louisville/news/20...,Series A,$12,United States,31.3.2020,EasyPost lays off 32 Louisville workers\nWe'd ...

In [36]:
df_no_duplicates['text'] = df_no_duplicates['text'].astype(str)

C:\Users\zpjev\AppData\Local\Temp\ipykernel_17816\82599811.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_no_duplicates['text'] = df_no_duplicates['text'].astype(str)

In [37]:
df_no_duplicates.to_csv("ocisteny_layoffs.csv", index=False)
df_no_duplicates

,index,Company,Location HQ,# Laid Off,Date,%,Industry,url,Stage,$ Raised (mm),Country,Date Added,text
0,0,Tract,"London,Non-U.S.",NaN,3.4.2025,NaN,Real Estate,https://sifted.eu/articles/ai-proptech-startup...,Unknown,NaN,United Kingdom,6.4.2025,"AI proptech startup Tract shuts down\nTract, t..."
1,1,Automattic,SF Bay Area,281.0,2.4.2025,16%,Other,https://techcrunch.com/2025/04/02/wordpress-ma...,Series E,$986,United States,2.4.2025,WordPress maker Automattic lays off 16% of sta...
2,2,Canva,"Sydney,Non-U.S.",10.0,2.4.2025,NaN,Consumer,https://www.afr.com/technology/canva-shocks-em...,Unknown,$2500,Australia,2.4.2025,"Piano • Client Dashboard\nApr 2, 2025 – 8.00pm..."
3,3,WhyHive,"Melbourne,Non-U.S.",NaN,2.4.2025,100%,Data,https://www.startupdaily.net/topic/business/da...,Seed,NaN,Australia,6.4.2025,Data analytics startup WhyHive is shutting dow...
4,4,Northvolt,"Stockholm,Non-U.S.",2800.0,31.3.2025,62%,Energy,https://sifted.eu/articles/northvolt-lays-off-...,Unknown,$13800,Sweden,1.4.2025,Northvolt lays off half of staff as bankrupt b...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4137,4021,Service,Los Angeles,NaN,16.3.2020,100%,Travel,https://techcrunch.com/2020/03/16/travel-savin...,Seed,$5,United States,31.8.2020,nan
4138,4022,HopSkipDrive,Los Angeles,8.0,13.3.2020,10%,Transportation,https://layoffs.fyi/2020/04/02/hopskipdrive-la...,Unknown,$45,United States,3.4.2020,[Layoff list ] EXCLUSIVE: HopSkipDrive laid of...
4139,4023,Panda Squad,SF Bay Area,6.0,13.3.2020,75%,Consumer,https://twitter.com/danielsinger/status/123854...,Seed,$1,United States,17.4.2020,nan
4140,4024,Tamara Mellon,Los Angeles,20.0,12.3.2020,40%,Retail,https://layoffs.fyi/list/tamara-mellon/,Series C,$90,United States,31.3.2020,Tamara Mellon layoffs 3/12/20 - Google Sheets\...
4141,4025,EasyPost,Salt Lake City,75.0,11.3.2020,NaN,Logistics,https://www.bizjournals.com/louisville/news/20...,Series A,$12,United States,31.3.2020,EasyPost lays off 32 Louisville workers\nWe'd ...

In [ ]:
df_nedele = pd.read_json('dataset_nedele_2.json')
df_nedele['url'] = df_nedele['url'].str.strip()
df_nedele.to_csv("nedelni_layoffs.csv", index=False)
df_nedele = df_nedele.drop_duplicates(subset="url")

,url,crawl,metadata,screenshotUrl,text,markdown,debug
0,https://www.theverge.com/2024/4/30/24145621/te...,{'loadedUrl': 'https://www.theverge.com/2024/4...,{'canonicalUrl': 'https://www.theverge.com/202...,NaN,Tesla layoffs hit Supercharger team just as it...,# Tesla layoffs hit Supercharger team just as ...,{'requestHandlerMode': 'browser'}
1,https://www.calcalistech.com/ctechnews/article...,{'loadedUrl': 'https://www.calcalistech.com/ct...,{'canonicalUrl': 'https://www.calcalistech.com...,NaN,"Fintech startup RiseUp, that helps customers c...","# Fintech startup RiseUp, that helps customers...",{'requestHandlerMode': 'browser'}
2,https://www.calcalistech.com/ctechnews/article...,{'loadedUrl': 'https://www.calcalistech.com/ct...,{'canonicalUrl': 'https://www.calcalistech.com...,NaN,From $200 million valuation to insolvency: Ins...,# From $200 million valuation to insolvency: I...,{'requestHandlerMode': 'browser'}
3,https://investors.akiliinteractive.com/news/ne...,{'loadedUrl': 'https://www.akiliinteractive.co...,{'canonicalUrl': 'https://www.akiliinteractive...,NaN,Akili Interactive\nIntroducing EndeavorOTC™ - ...,# Akili Interactive\n\n![](https://images.squa...,{'requestHandlerMode': 'browser'}
4,https://techcrunch.com/2024/04/29/indian-ride-...,{'loadedUrl': 'https://techcrunch.com/2024/04/...,{'canonicalUrl': 'https://techcrunch.com/2024/...,NaN,"India's Ola removes CEO in four months, cuts 1...","# India's Ola removes CEO in four months, cuts...",{'requestHandlerMode': 'browser'}
...,...,...,...,...,...,...,...
6752,https://www.youtube.com/watch?v=AK2tDagkLpo,{'loadedUrl': 'https://www.youtube.com/watch?v...,{'canonicalUrl': 'https://www.youtube.com/watc...,NaN,EWTN News Nightly - 2025-04-25 - EWTN News Nig...,# EWTN News Nightly - 2025-04-25 - EWTN News N...,{'requestHandlerMode': 'browser'}
6753,https://www.youtube.com/watch?v=m565WO-_Xjs,{'loadedUrl': 'https://www.youtube.com/watch?v...,{'canonicalUrl': 'https://www.youtube.com/watc...,NaN,"Cardinals seal Pope Francis’ coffin, formally ...","# Cardinals seal Pope Francis’ coffin, formall...",{'requestHandlerMode': 'browser'}
6754,https://www.youtube.com/watch?v=qf1_-pQ029M,{'loadedUrl': 'https://www.youtube.com/watch?v...,{'canonicalUrl': 'https://www.youtube.com/watc...,NaN,ABC World News Tonight with David Muir Full Br...,# ABC World News Tonight with David Muir Full ...,{'requestHandlerMode': 'browser'}
6755,https://www.youtube.com/watch?v=n1OmjbRtghw,{'loadedUrl': 'https://www.youtube.com/watch?v...,{'canonicalUrl': 'https://www.youtube.com/watc...,NaN,Ep. 16 - A citizen's guide to resisting Trump ...,# Ep. 16 - A citizen's guide to resisting Trum...,{'requestHandlerMode': 'browser'}
6756,https://www.youtube.com/watch?v=6gBwOgSe3yo,{'loadedUrl': 'https://www.youtube.com/watch?v...,{'canonicalUrl': 'https://www.youtube.com/watc...,NaN,Jon Stewart & Heather McGhee discuss Anti-DEI ...,# Jon Stewart & Heather McGhee discuss Anti-DE...,{'requestHandlerMode': 'browser'}

In [ ]:
df_carodejnice.to_csv("posledni_layoffs.csv", index=False)
df_carodejnice = df_carodejnice.drop_duplicates(subset="url")

,url,crawl,metadata,screenshotUrl,text,markdown,debug
0,https://www.sfchronicle.com/tech/article/tech-...,{'loadedUrl': 'https://www.sfchronicle.com/tec...,{'canonicalUrl': 'https://www.sfchronicle.com/...,NaN,Google and Rivian cut dozens of jobs\nGoogle h...,# Google and Rivian cut dozens of jobs\n\nGoog...,{'requestHandlerMode': 'browser'}
1,https://www.moneycontrol.com/technology/bnpl-s...,{'loadedUrl': 'https://www.moneycontrol.com/te...,{'canonicalUrl': 'https://www.moneycontrol.com...,NaN,BNPL startup Simpl lays off around 160 employe...,# BNPL startup Simpl lays off around 160 emplo...,{'requestHandlerMode': 'browser'}
2,https://economictimes.indiatimes.com/tech/tech...,{'loadedUrl': 'https://economictimes.indiatime...,{'canonicalUrl': 'https://m.economictimes.com/...,NaN,Good Glam layoffs: Content-to-commerce platfor...,# Good Glam layoffs: Content-to-commerce platf...,{'requestHandlerMode': 'browser'}
3,https://www.sfgate.com/tech/article/ghost-auto...,{'loadedUrl': 'https://www.sfgate.com/tech/art...,{'canonicalUrl': 'https://www.sfgate.com/tech/...,NaN,"Bay Area tech startup shuts down, lays off 100...","# Bay Area tech startup shuts down, lays off 1...",{'requestHandlerMode': 'browser'}
4,https://www.bizjournals.com/southflorida/news/...,{'loadedUrl': 'https://www.bizjournals.com/sou...,{'canonicalUrl': 'https://www.bizjournals.com/...,NaN,Kaseya cuts at least 150 staff in Miami and ot...,# Kaseya cuts at least 150 staff in Miami and ...,{'requestHandlerMode': 'browser'}
...,...,...,...,...,...,...,...
1206,https://www.bizjournals.com/boston/news/2024/1...,{'loadedUrl': 'https://www.bizjournals.com/bos...,{'canonicalUrl': 'https://www.bizjournals.com/...,NaN,Akamai layoffs 2024: Company cuts 2.5% of its ...,# Akamai layoffs 2024: Company cuts 2.5% of it...,{'requestHandlerMode': 'browser'}
1207,https://www.sfgate.com/tech/article/applovin-l...,{'loadedUrl': 'https://www.sfgate.com/tech/art...,{'canonicalUrl': 'https://www.sfgate.com/tech/...,NaN,Bay Area tech company AppLovin announces layof...,# Bay Area tech company AppLovin announces lay...,{'requestHandlerMode': 'browser'}
1208,https://www.bizjournals.com/portland/news/2024...,{'loadedUrl': 'https://www.bizjournals.com/por...,{'canonicalUrl': 'https://www.bizjournals.com/...,NaN,Private equity-owned New Relic has more layoff...,# Private equity-owned New Relic has more layo...,{'requestHandlerMode': 'browser'}
1209,https://pitchbook.com/news/articles/bowery-ind...,{'loadedUrl': 'https://pitchbook.com/news/arti...,{'canonicalUrl': 'https://pitchbook.com/news/a...,NaN,"Bowery, once a leading indoor farming company ...","# Bowery, once a leading indoor farming compan...",{'requestHandlerMode': 'browser'}
1210,https://www.sfgate.com/tech/article/enphase-en...,{'loadedUrl': 'https://www.sfgate.com/tech/art...,{'canonicalUrl': 'https://www.sfgate.com/tech/...,NaN,"Down 80% in value since 2022, Bay Area solar g...","# Down 80% in value since 2022, Bay Area solar...",{'requestHandlerMode': 'browser'}

In [ ]:
df_merge_nedele = pd.merge(df_no_duplicates, df_nedele, on='url', how='left')

,index,Company,Location HQ,# Laid Off,Date,%,Industry,url,Stage,$ Raised (mm),Country,Date Added,text_x,crawl,metadata,screenshotUrl,text_y,markdown,debug
0,0,Tract,"London,Non-U.S.",NaN,3.4.2025,NaN,Real Estate,https://sifted.eu/articles/ai-proptech-startup...,Unknown,NaN,United Kingdom,6.4.2025,"AI proptech startup Tract shuts down\nTract, t...",NaN,NaN,NaN,NaN,NaN,NaN
1,1,Automattic,SF Bay Area,281.0,2.4.2025,16%,Other,https://techcrunch.com/2025/04/02/wordpress-ma...,Series E,$986,United States,2.4.2025,WordPress maker Automattic lays off 16% of sta...,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Canva,"Sydney,Non-U.S.",10.0,2.4.2025,NaN,Consumer,https://www.afr.com/technology/canva-shocks-em...,Unknown,$2500,Australia,2.4.2025,"Piano • Client Dashboard\nApr 2, 2025 – 8.00pm...",NaN,NaN,NaN,NaN,NaN,NaN
3,3,WhyHive,"Melbourne,Non-U.S.",NaN,2.4.2025,100%,Data,https://www.startupdaily.net/topic/business/da...,Seed,NaN,Australia,6.4.2025,Data analytics startup WhyHive is shutting dow...,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Northvolt,"Stockholm,Non-U.S.",2800.0,31.3.2025,62%,Energy,https://sifted.eu/articles/northvolt-lays-off-...,Unknown,$13800,Sweden,1.4.2025,Northvolt lays off half of staff as bankrupt b...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4021,4021,Service,Los Angeles,NaN,16.3.2020,100%,Travel,https://techcrunch.com/2020/03/16/travel-savin...,Seed,$5,United States,31.8.2020,nan,NaN,NaN,NaN,NaN,NaN,NaN
4022,4022,HopSkipDrive,Los Angeles,8.0,13.3.2020,10%,Transportation,https://layoffs.fyi/2020/04/02/hopskipdrive-la...,Unknown,$45,United States,3.4.2020,[Layoff list ] EXCLUSIVE: HopSkipDrive laid of...,{'loadedUrl': 'https://layoffs.fyi/2020/04/02/...,{'canonicalUrl': 'https://layoffs.fyi/2020/04/...,NaN,[Layoff list ] EXCLUSIVE: HopSkipDrive laid of...,# \[Layoff list \] EXCLUSIVE: HopSkipDrive lai...,{'requestHandlerMode': 'http'}
4023,4023,Panda Squad,SF Bay Area,6.0,13.3.2020,75%,Consumer,https://twitter.com/danielsinger/status/123854...,Seed,$1,United States,17.4.2020,nan,NaN,NaN,NaN,NaN,NaN,NaN
4024,4024,Tamara Mellon,Los Angeles,20.0,12.3.2020,40%,Retail,https://layoffs.fyi/list/tamara-mellon/,Series C,$90,United States,31.3.2020,Tamara Mellon layoffs 3/12/20 - Google Sheets\...,{'loadedUrl': 'https://docs.google.com/spreads...,{'canonicalUrl': 'https://docs.google.com/spre...,NaN,Tamara Mellon layoffs 3/12/20 - Google Sheets\...,# Tamara Mellon layoffs 3/12/20 - Google Sheet...,{'requestHandlerMode': 'http'}
4025,4025,EasyPost,Salt Lake City,75.0,11.3.2020,NaN,Logistics,https://www.bizjournals.com/louisville/news/20...,Series A,$12,United States,31.3.2020,EasyPost lays off 32 Louisville workers\nWe'd ...,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_final_merge = pd.merge(df_merge_nedele, df_carodejnice, on='url', how='left')

,index,Company,Location HQ,# Laid Off,Date,%,Industry,url,Stage,$ Raised (mm),...,screenshotUrl_x,text_y,markdown_x,debug_x,crawl_y,metadata_y,screenshotUrl_y,text,markdown_y,debug_y
0,0,Tract,"London,Non-U.S.",NaN,3.4.2025,NaN,Real Estate,https://sifted.eu/articles/ai-proptech-startup...,Unknown,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Automattic,SF Bay Area,281.0,2.4.2025,16%,Other,https://techcrunch.com/2025/04/02/wordpress-ma...,Series E,$986,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Canva,"Sydney,Non-U.S.",10.0,2.4.2025,NaN,Consumer,https://www.afr.com/technology/canva-shocks-em...,Unknown,$2500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,WhyHive,"Melbourne,Non-U.S.",NaN,2.4.2025,100%,Data,https://www.startupdaily.net/topic/business/da...,Seed,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Northvolt,"Stockholm,Non-U.S.",2800.0,31.3.2025,62%,Energy,https://sifted.eu/articles/northvolt-lays-off-...,Unknown,$13800,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4021,4021,Service,Los Angeles,NaN,16.3.2020,100%,Travel,https://techcrunch.com/2020/03/16/travel-savin...,Seed,$5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4022,4022,HopSkipDrive,Los Angeles,8.0,13.3.2020,10%,Transportation,https://layoffs.fyi/2020/04/02/hopskipdrive-la...,Unknown,$45,...,NaN,[Layoff list ] EXCLUSIVE: HopSkipDrive laid of...,# \[Layoff list \] EXCLUSIVE: HopSkipDrive lai...,{'requestHandlerMode': 'http'},{'loadedUrl': 'https://layoffs.fyi/2020/04/02/...,{'canonicalUrl': 'https://layoffs.fyi/2020/04/...,NaN,[Layoff list ] EXCLUSIVE: HopSkipDrive laid of...,# \[Layoff list \] EXCLUSIVE: HopSkipDrive lai...,{'requestHandlerMode': 'http'}
4023,4023,Panda Squad,SF Bay Area,6.0,13.3.2020,75%,Consumer,https://twitter.com/danielsinger/status/123854...,Seed,$1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4024,4024,Tamara Mellon,Los Angeles,20.0,12.3.2020,40%,Retail,https://layoffs.fyi/list/tamara-mellon/,Series C,$90,...,NaN,Tamara Mellon layoffs 3/12/20 - Google Sheets\...,# Tamara Mellon layoffs 3/12/20 - Google Sheet...,{'requestHandlerMode': 'http'},{'loadedUrl': 'https://docs.google.com/spreads...,{'canonicalUrl': 'https://docs.google.com/spre...,NaN,Tamara Mellon layoffs 3/12/20 - Google Sheets\...,# Tamara Mellon layoffs 3/12/20 - Google Sheet...,{'requestHandlerMode': 'http'}
4025,4025,EasyPost,Salt Lake City,75.0,11.3.2020,NaN,Logistics,https://www.bizjournals.com/louisville/news/20...,Series A,$12,...,NaN,NaN,NaN,NaN,{'loadedUrl': 'https://www.bizjournals.com/lou...,{'canonicalUrl': 'https://www.bizjournals.com/...,NaN,EasyPost lays off 32 Louisville workers\nWe'd ...,# EasyPost lays off 32 Louisville workers\n\nW...,{'requestHandlerMode': 'browser'}

In [44]:
df = pd.read_csv("posledni_layoffs.csv", encoding='utf-8') 
df_final_merge = df[df['text'].notna()]
df_final_merge['text'] = df_final_merge['text'].astype(str)

# prázdný list, kam si budu ukládat odpovědi chatu
results = []

# tady začíná for loop. df.head(3) říká, že loop proběhne pouze první tři řádky dataframu.
# Toto číslo můžete zvýšit, popř. head úplně odstranit, až budete mít odladěný prompt.
for index, row in df_merge_nedele.iterrows():

    # do proměnných si uložím id zvířete a obsah ze sloupce concatenated, kde je úplně vše z předchozích sloupců.
    # můžete si vytvořit vlastní proměnné pouze z těch sloupců, které vy konkrétně potřebujete.
    index_clanku = row['index']
    text_clanku = row['text']
    
    # printy jsou zde na prohlížení a odladění. V reálu byste je pak zakomentovaly.
    # print(index_clanku)
    # print(text_clanku)

    # tady je vám dobře známý completions :-)
    # krom změn system message a user message můžete přidat ještě assistant message na přidání příkladu
    # můžete přidat parametr temperature, max_tokens aneb response_format, máte-li vhodnou verzi pythonu
    completion = client.chat.completions.create(
                    model="gpt-4o-mini",
                    messages=[
                            {"role": "system",
                             "content": "You are given an article that contains an information of a lay off of a company. Read the article and evaluate whether it contain a reason of the lay off. Provide answer as a single word. Return YES if the article contains the reason and NO if it does not contain the reason."},
                            {"role": "user",
                             "content": "here is the article:" + text_clanku}
                            ]
                    )
    
    # zde vyextrahujete obsah odpovědi
    response_text = completion.choices[0].message.content
    
    # a odpověď si vyprintíte - můžete později zakomentovat
    print("odpoved:")
    # print(response_text)
    # print("-----------------")
    # print()

    # výsledek aktuálního běhu for loopu uložíte do listu results
    results.append({
        'id': index_clanku,
        'odpoved': response_text
    })

# PRŮBĚŽNÉ UKLÁDÁNÍ každých 5 článků - dořešit aby to ukazovalo vždy když se udělá průběžné ukládání
    if (index + 1) % 5 == 0:
        df_results = pd.DataFrame(results)
        df_results.to_csv("je_tam_duvod_vypovedi_prubezne.csv", index=False)
        print(f"Průběžně uloženo {len(results)} výsledků do souboru.")
        

# Konečné uložení po ukončení celého cyklu
df_results = pd.DataFrame(results)
df_results.to_csv("je_tam_duvod_vypovedi.csv", index=False)
# print("Finální uložení hotovo.")

C:\Users\zpjev\AppData\Local\Temp\ipykernel_17816\3485766200.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final_merge['text'] = df_final_merge['text'].astype(str)

odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 5 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 10 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 15 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 20 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 25 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 30 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 34 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 38 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 43 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 47 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 52 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 57 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 62 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 66 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 71 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 76 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 81 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 86 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 91 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 96 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 101 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 106 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 110 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 115 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 120 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 133 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 141 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 145 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 150 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 154 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 158 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 163 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 167 výsledků do souboru.
odpoved:
odpoved:
odpoved:
Průběžně uloženo 170 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 175 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 179 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 183 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 192 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 197 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 202 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 207 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 212 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 216 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 221 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 225 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 230 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 235 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 240 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 245 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 249 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 254 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 259 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 266 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 278 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 282 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 287 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 291 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 295 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 299 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 308 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 313 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 318 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 327 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 332 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 337 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 342 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 347 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 351 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 356 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 361 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 366 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 371 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 375 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 380 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 385 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 390 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 395 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 400 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 404 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 409 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 414 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 419 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 424 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 429 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 433 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 437 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 441 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 446 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 454 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 459 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 464 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 469 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 474 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 479 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 484 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 488 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 493 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 497 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 502 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 511 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 518 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 523 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 528 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 532 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 537 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 542 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 547 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 552 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 557 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 562 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 566 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 571 výsledků do souboru.
odpoved:
odpoved:
odpoved:
Průběžně uloženo 574 výsledků do souboru.
odpoved:
odpoved:
odpoved:
Průběžně uloženo 577 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 582 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 590 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 594 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 599 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 604 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 609 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 614 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 618 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 622 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 631 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 636 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 640 výsledků do souboru.
odpoved:
odpoved:
odpoved:
Průběžně uloženo 643 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 648 výsledků do souboru.
odpoved:
odpoved:
odpoved:
Průběžně uloženo 651 výsledků do souboru.
odpoved:
odpoved:
odpoved:
Průběžně uloženo 654 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 659 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 664 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 668 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 673 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 678 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 683 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 691 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 696 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 700 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 705 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 710 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 714 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 718 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 723 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 728 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 733 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 737 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 742 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 747 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 752 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 756 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 761 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 766 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 771 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 776 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 780 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 787 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 792 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 797 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 801 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 805 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 810 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 815 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 820 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 825 výsledků do souboru.
odpoved:
odpoved:
odpoved:
Průběžně uloženo 828 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 833 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 838 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 842 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 847 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 852 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 856 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 860 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 865 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 870 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 875 výsledků do souboru.
odpoved:
odpoved:
odpoved:
Průběžně uloženo 878 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 884 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 888 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 892 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 896 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 901 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 906 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 910 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 915 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 919 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 924 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 929 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 933 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 938 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 942 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 946 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 950 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 954 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 958 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 963 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 968 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 979 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 984 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 989 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 993 výsledků do souboru.
odpoved:
odpoved:
Průběžně uloženo 995 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 1004 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 1009 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 1014 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 1019 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 1025 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 1030 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 1035 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 1043 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 1052 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 1056 výsledků do souboru.
odpoved:
odpoved:
Průběžně uloženo 1058 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 1062 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 1067 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 1072 výsledků do souboru.
odpoved:
odpoved:
odpoved:
Průběžně uloženo 1075 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 1082 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 1086 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 1091 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 1096 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 1101 výsledků do souboru.
odpoved:
odpoved:
odpoved:
Průběžně uloženo 1104 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 1108 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 1113 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 1117 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 1125 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 1130 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 1135 výsledků do souboru.
odpoved:
odpoved:
odpoved:
Průběžně uloženo 1138 výsledků do souboru.
odpoved:
odpoved:
odpoved:
odpoved:
odpoved:
Průběžně uloženo 1143 výsledků do souboru.

RateLimitError: Error code: 429 - {'error': {'message': 'Request too large for gpt-4o-mini in organization org-Z2r258WZnMVeUQhaTxSRaqZt on tokens per min (TPM): Limit 200000, Requested 251891. The input or output tokens must be reduced in order to run successfully. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

In [2]:
df_zkouska = pd.read_csv('kategorizace_prubezne.csv')
df_zkouska

,id,zkraceny,odpoved,main_category,sub_category
0,0,"Tract, an AI proptech startup based in London,...",YES,Financial Health,Funding Shortage
1,1,"Automattic, the company behind WordPress.com a...",YES,Operational Efficiency & Performance,Performance-based Restructuring
2,2,Canva has announced its first-ever redundancy ...,YES,Technological Change,Automation & AI Adoption
3,3,Data analytics startup WhyHive is shutting dow...,YES,Financial Health,Revenue Decline
4,5,"2U/edX has executed another round of layoffs, ...",YES,Financial Health,Funding Shortage
...,...,...,...,...,...
1666,2718,Loop Insurance laid off approximately 15 emplo...,YES,Financial Health,Funding Shortage
1667,2719,"Pix, a Napa wine startup, recently laid off th...",YES,Financial Health,Funding Shortage
1668,2720,"Tier Mobility, a German micromobility company,...",YES,Financial Health,Funding Shortage
1669,2725,DataRobot has announced it will lay off 26% of...,YES,Financial Health,Revenue Decline
1670,2726,"Kogan, the Australian online retailer, has ann...",YES,Financial Health,Revenue Decline

In [ ]:
df_results.tail(3)

,index,Company,Location HQ,# Laid Off,Date,%,Industry,url,Stage,$ Raised (mm),Country,Date Added,text
4022,4022,HopSkipDrive,Los Angeles,8.0,13.3.2020,10%,Transportation,https://layoffs.fyi/2020/04/02/hopskipdrive-la...,Unknown,$45,United States,3.4.2020,[Layoff list ] EXCLUSIVE: HopSkipDrive laid of...
4024,4024,Tamara Mellon,Los Angeles,20.0,12.3.2020,40%,Retail,https://layoffs.fyi/list/tamara-mellon/,Series C,$90,United States,31.3.2020,Tamara Mellon layoffs 3/12/20 - Google Sheets\...
4025,4025,EasyPost,Salt Lake City,75.0,11.3.2020,NaN,Logistics,https://www.bizjournals.com/louisville/news/20...,Series A,$12,United States,31.3.2020,EasyPost lays off 32 Louisville workers\nWe'd ...