In [1]:
import pandas as pd
import json
import csv

In [3]:
df_data = pd.read_csv("ocisteny_layoffs.csv")
df_duvod = pd.read_csv("je_tam_duvod_vypovedi.csv")
df_duvod = df_duvod.rename(columns = {'id' : 'index'})
df_dataset = pd.merge(df_data, df_duvod, how='left')
df_dataset.to_csv('duvody_v_layoffs_14_05.csv')
df_dataset

,index,Company,Location HQ,# Laid Off,Date,%,Industry,url,Stage,$ Raised (mm),Country,Date Added,text,odpoved
0,0,Tract,"London,Non-U.S.",NaN,3.4.2025,NaN,Real Estate,https://sifted.eu/articles/ai-proptech-startup...,Unknown,NaN,United Kingdom,6.4.2025,"AI proptech startup Tract shuts down\nTract, t...",YES
1,1,Automattic,SF Bay Area,281.0,2.4.2025,16%,Other,https://techcrunch.com/2025/04/02/wordpress-ma...,Series E,$986,United States,2.4.2025,WordPress maker Automattic lays off 16% of sta...,YES
2,2,Canva,"Sydney,Non-U.S.",10.0,2.4.2025,NaN,Consumer,https://www.afr.com/technology/canva-shocks-em...,Unknown,$2500,Australia,2.4.2025,"Piano • Client Dashboard\nApr 2, 2025 – 8.00pm...",YES
3,3,WhyHive,"Melbourne,Non-U.S.",NaN,2.4.2025,100%,Data,https://www.startupdaily.net/topic/business/da...,Seed,NaN,Australia,6.4.2025,Data analytics startup WhyHive is shutting dow...,YES
4,4,Northvolt,"Stockholm,Non-U.S.",2800.0,31.3.2025,62%,Energy,https://sifted.eu/articles/northvolt-lays-off-...,Unknown,$13800,Sweden,1.4.2025,Northvolt lays off half of staff as bankrupt b...,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4021,4021,Service,Los Angeles,NaN,16.3.2020,100%,Travel,https://techcrunch.com/2020/03/16/travel-savin...,Seed,$5,United States,31.8.2020,NaN,NaN
4022,4022,HopSkipDrive,Los Angeles,8.0,13.3.2020,10%,Transportation,https://layoffs.fyi/2020/04/02/hopskipdrive-la...,Unknown,$45,United States,3.4.2020,[Layoff list ] EXCLUSIVE: HopSkipDrive laid of...,YES
4023,4023,Panda Squad,SF Bay Area,6.0,13.3.2020,75%,Consumer,https://twitter.com/danielsinger/status/123854...,Seed,$1,United States,17.4.2020,NaN,NaN
4024,4024,Tamara Mellon,Los Angeles,20.0,12.3.2020,40%,Retail,https://layoffs.fyi/list/tamara-mellon/,Series C,$90,United States,31.3.2020,Tamara Mellon layoffs 3/12/20 - Google Sheets\...,NO
4025,4025,EasyPost,Salt Lake City,75.0,11.3.2020,NaN,Logistics,https://www.bizjournals.com/louisville/news/20...,Series A,$12,United States,31.3.2020,EasyPost lays off 32 Louisville workers\nWe'd ...,NO

In [4]:
df = pd.read_csv('ocistene_komplet.csv')
df

,index,Company,Location HQ,# Laid Off,Date,%,Industry,url,Stage,$ Raised (mm),...,screenshotUrl_x,text_y,markdown_x,debug_x,crawl_y,metadata_y,screenshotUrl_y,text,markdown_y,debug_y
0,0,Tract,"London,Non-U.S.",NaN,3.4.2025,NaN,Real Estate,https://sifted.eu/articles/ai-proptech-startup...,Unknown,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Automattic,SF Bay Area,281.0,2.4.2025,16%,Other,https://techcrunch.com/2025/04/02/wordpress-ma...,Series E,$986,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Canva,"Sydney,Non-U.S.",10.0,2.4.2025,NaN,Consumer,https://www.afr.com/technology/canva-shocks-em...,Unknown,$2500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,WhyHive,"Melbourne,Non-U.S.",NaN,2.4.2025,100%,Data,https://www.startupdaily.net/topic/business/da...,Seed,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Northvolt,"Stockholm,Non-U.S.",2800.0,31.3.2025,62%,Energy,https://sifted.eu/articles/northvolt-lays-off-...,Unknown,$13800,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4021,4021,Service,Los Angeles,NaN,16.3.2020,100%,Travel,https://techcrunch.com/2020/03/16/travel-savin...,Seed,$5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4022,4022,HopSkipDrive,Los Angeles,8.0,13.3.2020,10%,Transportation,https://layoffs.fyi/2020/04/02/hopskipdrive-la...,Unknown,$45,...,NaN,[Layoff list ] EXCLUSIVE: HopSkipDrive laid of...,# \[Layoff list \] EXCLUSIVE: HopSkipDrive lai...,{'requestHandlerMode': 'http'},{'loadedUrl': 'https://layoffs.fyi/2020/04/02/...,{'canonicalUrl': 'https://layoffs.fyi/2020/04/...,NaN,[Layoff list ] EXCLUSIVE: HopSkipDrive laid of...,# \[Layoff list \] EXCLUSIVE: HopSkipDrive lai...,{'requestHandlerMode': 'http'}
4023,4023,Panda Squad,SF Bay Area,6.0,13.3.2020,75%,Consumer,https://twitter.com/danielsinger/status/123854...,Seed,$1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4024,4024,Tamara Mellon,Los Angeles,20.0,12.3.2020,40%,Retail,https://layoffs.fyi/list/tamara-mellon/,Series C,$90,...,NaN,Tamara Mellon layoffs 3/12/20 - Google Sheets\...,# Tamara Mellon layoffs 3/12/20 - Google Sheet...,{'requestHandlerMode': 'http'},{'loadedUrl': 'https://docs.google.com/spreads...,{'canonicalUrl': 'https://docs.google.com/spre...,NaN,Tamara Mellon layoffs 3/12/20 - Google Sheets\...,# Tamara Mellon layoffs 3/12/20 - Google Sheet...,{'requestHandlerMode': 'http'}
4025,4025,EasyPost,Salt Lake City,75.0,11.3.2020,NaN,Logistics,https://www.bizjournals.com/louisville/news/20...,Series A,$12,...,NaN,NaN,NaN,NaN,{'loadedUrl': 'https://www.bizjournals.com/lou...,{'canonicalUrl': 'https://www.bizjournals.com/...,NaN,EasyPost lays off 32 Louisville workers\nWe'd ...,# EasyPost lays off 32 Louisville workers\n\nW...,{'requestHandlerMode': 'browser'}